OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-yUiGr5Uis41lNvLc5a909249B1A945DaAaF197D032A342A6"
  base_url: "https://api.xiaoai.plus/v1"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"
  target_language: "日文"